services:

  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3-management
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${RABBIT_PORT}:${RABBIT_PORT}

  bot:
    container_name: bot
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - rabbitmq

volumes:
  postgres_ii_volume:

